# Generated by Django 3.1.14 on 2023-02-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
